=begin
#Live Validation Service Client

#Client that can be used to access Live Validation Service.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require "uri"

module SwaggerClient
  class WhitelistApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # 
    # Get list of safe properties is prod environments.
    # @param [Hash] opts the optional parameters
    # @return [LiveValidationWhiteListResponse]
    def tools_live_validation_prod_white_list(opts = {})
      data, _status_code, _headers = tools_live_validation_prod_white_list_with_http_info(opts)
      return data
    end

    # 
    # Get list of safe properties is prod environments.
    # @param [Hash] opts the optional parameters
    # @return [Array<(LiveValidationWhiteListResponse, Fixnum, Hash)>] LiveValidationWhiteListResponse data, response status code and response headers
    def tools_live_validation_prod_white_list_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: WhitelistApi.tools_live_validation_prod_white_list ..."
      end
      # resource path
      local_var_path = "/prod/whitelist"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'LiveValidationWhiteListResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: WhitelistApi#tools_live_validation_prod_white_list\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # Get list of safe properties in non-prod canary environments.
    # @param [Hash] opts the optional parameters
    # @return [LiveValidationWhiteListResponse]
    def tools_live_validation_white_list(opts = {})
      data, _status_code, _headers = tools_live_validation_white_list_with_http_info(opts)
      return data
    end

    # 
    # Get list of safe properties in non-prod canary environments.
    # @param [Hash] opts the optional parameters
    # @return [Array<(LiveValidationWhiteListResponse, Fixnum, Hash)>] LiveValidationWhiteListResponse data, response status code and response headers
    def tools_live_validation_white_list_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: WhitelistApi.tools_live_validation_white_list ..."
      end
      # resource path
      local_var_path = "/whitelist"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'LiveValidationWhiteListResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: WhitelistApi#tools_live_validation_white_list\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
