=begin
#Live Validation Service Client

#Client that can be used to access Live Validation Service.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::WhitelistApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WhitelistApi' do
  before do
    # run before each test
    @instance = SwaggerClient::WhitelistApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WhitelistApi' do
    it 'should create an instance of WhitelistApi' do
      expect(@instance).to be_instance_of(SwaggerClient::WhitelistApi)
    end
  end

  # unit tests for tools_live_validation_prod_white_list
  # 
  # Get list of safe properties is prod environments.
  # @param [Hash] opts the optional parameters
  # @return [LiveValidationWhiteListResponse]
  describe 'tools_live_validation_prod_white_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for tools_live_validation_white_list
  # 
  # Get list of safe properties in non-prod canary environments.
  # @param [Hash] opts the optional parameters
  # @return [LiveValidationWhiteListResponse]
  describe 'tools_live_validation_white_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
