=begin
#Live Validation Service Client

#Client that can be used to access Live Validation Service.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::LiveValidationWhiteListResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LiveValidationWhiteListResponse' do
  before do
    # run before each test
    @instance = SwaggerClient::LiveValidationWhiteListResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LiveValidationWhiteListResponse' do
    it 'should create an instance of LiveValidationWhiteListResponse' do
      expect(@instance).to be_instance_of(SwaggerClient::LiveValidationWhiteListResponse)
    end
  end
  describe 'test attribute "safe_properties"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

