=begin
#Live Validation Service Client

#Client that can be used to access Live Validation Service.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::LiveValidationResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LiveValidationResponse' do
  before do
    # run before each test
    @instance = SwaggerClient::LiveValidationResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LiveValidationResponse' do
    it 'should create an instance of LiveValidationResponse' do
      expect(@instance).to be_instance_of(SwaggerClient::LiveValidationResponse)
    end
  end
  describe 'test attribute "request_validation_result"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "response_validation_result"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "errors"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

