=begin
#Live Validation Service Client

#Client that can be used to access Live Validation Service.

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/live_request'
require 'swagger_client/models/live_response'
require 'swagger_client/models/live_validation_parameter'
require 'swagger_client/models/live_validation_response'
require 'swagger_client/models/live_validation_white_list_response'
require 'swagger_client/models/request_validation_result'
require 'swagger_client/models/response_validation_result'

# APIs
require 'swagger_client/api/live_validation_api'
require 'swagger_client/api/prod_validate_api'
require 'swagger_client/api/validate_api'
require 'swagger_client/api/whitelist_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
